# Generated by Django 6.0.3 on 2026-05-14 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_task_fields'),
        ('clients', '0003_client_phone'),
        ('deals', '0004_deal_assignment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='automation_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('automation_key__isnull', False), ('is_completed', False)), fields=('automation_key',), name='activity_open_task_unique_automation_key'),
        ),
    ]
