# Generated by Django 6.0.3 on 2026-05-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_automation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='archive_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tasks', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_manually_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='Task hidden from operational UI until this datetime.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
