# Generated by Django 6.0.3 on 2026-05-16 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companymember_permissions'),
        ('deals', '0004_deal_assignment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('stale', 'No recent activity'), ('closing_soon', 'Close date approaching'), ('no_contact', 'Client missing contact details'), ('high_value_idle', 'High-value deal needs attention'), ('overdue_task', 'Has overdue tasks'), ('long_in_stage', 'Longer than usual in stage')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_signals', to='companies.company')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='deals.deal')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active', 'severity'], name='deals_deals_company_90c4c2_idx'), models.Index(fields=['deal', 'is_active'], name='deals_deals_deal_id_bdf6bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'signal_type'), name='deal_signal_unique_type_per_deal')],
            },
        ),
    ]
