# Generated by Django 6.0.3 on 2026-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=5),
        ),
    ]
