# Generated by Django 6.0.3 on 2026-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20),
        ),
    ]
